"""

Revision ID: bfe9004d5237
Revises: 
Create Date: 2025-12-19 00:14:25.339742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe9004d5237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_level_enum = sa.Enum('L', 'M', name='subscriptionlevel')
    subscription_status_enum = sa.Enum('ACTIVE', 'CANCELED', name='subscriptionstatus')
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FAILED', 'SENT', name='messagestatus'), nullable=False),
    sa.Column('destination_topic', sa.String(length=64), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('rowversion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', subscription_level_enum, nullable=False),
    sa.Column('status', subscription_status_enum, nullable=False),
    sa.Column('pending_level', subscription_level_enum, nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level_change_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('outbox')
    # ### end Alembic commands ###
