services:
  # TODO: Rename to service name
  template:
    image: local/template:latest
    restart: unless-stopped
    networks:
      - microservices
      - rabbitmq

  template-postgres:
    image: postgres:17.4
    environment:
      - name=value

networks:
  microservices:
    external: true
