services:
  app:
    image: local/app:latest
    build: .
    ports:
      - 8000:8000
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  prometheus:
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    cgroup: host
    command:
      - --docker_only
      - --store_container_labels=true
      - --whitelisted_container_labels=com.docker.compose.project,com.docker.compose.service
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:roa
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - monitoring
    privileged: true

  grafana:
    image: grafana/grafana:12.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
