services:
  auth:
    image: local/auth:latest
    build:
      context: ".."
      dockerfile: "auth/Dockerfile"
    restart: no
    networks:
      # - microservices
      - auth-internal
    # ports:
    #   - 8001:8000
    env_file:
      - .dev/.env
    environment:
      - APP_DB__DSN=postgresql+asyncpg://auth:auth@auth-db:5432/auth
    volumes:
      - .dev/secrets:/var/run/secrets

  auth-db:
    image: postgres:17.4
    environment:
      - "POSTGRES_USER=auth"
      - "POSTGRES_PASSWORD=auth"
      - "POSTGRES_DB=auth"
    ports:
      - 15432:5432
    networks:
      - auth-internal
    volumes:
      - auth-pgdata:/var/lib/postgresql

networks:
  auth-internal:
    driver: bridge

volumes:
  auth-pgdata:
