"""add episode name description and duration

Revision ID: c61eac6399e1
Revises: dd0266072dec
Create Date: 2025-12-20 07:36:55.533782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61eac6399e1'
down_revision: Union[str, Sequence[str], None] = 'dd0266072dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('episodes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('episodes', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'duration')
    op.drop_column('episodes', 'description')
    op.drop_column('episodes', 'name')
    # ### end Alembic commands ###
