"""

Revision ID: bfe9004d5237
Revises:
Create Date: 2025-12-19 00:14:25.339742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfe9004d5237"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    company_status_enum = sa.Enum("active", "deleted", name="companystatus")
    content_owner_status_enum = sa.Enum(
        "active", "deleted", name="contentownerstatus"
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "FAILED",
                "SENT",
                name="messagestatus",
            ),
            nullable=False,
        ),
        sa.Column("destination_topic", sa.String(length=64), nullable=False),
        sa.Column("routing_key", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("tries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("process_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_timeout_ms", sa.Integer(), nullable=True),
        sa.Column("rowversion", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", company_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_owners",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "permissions",
            sa.ARRAY(sa.String(), as_tuple=True),
            nullable=False,
        ),
        sa.Column("status", content_owner_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_owners")
    op.drop_table("companies")
    op.drop_table("outbox")
    # ### end Alembic commands ###
