"""add outbox table

Revision ID: 63c254c9b216
Revises: d6277185d8c7
Create Date: 2025-12-17 18:53:06.278790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63c254c9b216"
down_revision: Union[str, Sequence[str], None] = "d6277185d8c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "FAILED", "SENT", name="messagestatus"),
            nullable=False,
        ),
        sa.Column("destination_topic", sa.String(length=64), nullable=False),
        sa.Column("routing_key", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("tries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("process_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_timeout_ms", sa.Integer(), nullable=True),
        sa.Column("rowversion", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    # ### end Alembic commands ###
